# Generated by Django 4.2.1 on 2023-08-18 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0003_pano_pintype_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='pintype',
        ),
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.FileField(upload_to='pin', verbose_name='Pin Resmi'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
